### ISSUE TITLE
Failing rspec test

### ISSUE THREAD

**Issue by xsuchy** [wvanbergen/scoped_search#34]
I'm trying to run spec you bundle in your project.

First I make sure it runs only on sqlite:

```
sed 5,15d -i spec/database.ruby.yml
```

then I run tests:

```
+ rspec spec
......................................................................................................................................F..........................................................................................................

Failures:

  1) ScopedSearch using a sqlite database using order resetting order when selecting distinct values
     Failure/Error: Set.new(distinct_search.map(&:explicit)).should == Set['baz', nil]
       expected: #<Set: {"baz", nil}>
            got: #<Set: {"baz"}> (using ==)
       Diff:
       @@ -1,2 +1,2 @@
       -#<Set: {"baz", nil}>
       +#<Set: {"baz"}>
     # /usr/share/gems/gems/rspec-expectations-2.8.0/lib/rspec/expectations/fail_with.rb:32:in `fail_with'
     # /usr/share/gems/gems/rspec-expectations-2.8.0/lib/rspec/matchers/operator_matcher.rb:47:in `fail_with_message'
     # /usr/share/gems/gems/rspec-expectations-2.8.0/lib/rspec/matchers/operator_matcher.rb:69:in `__delegate_operator'
     # /usr/share/gems/gems/rspec-expectations-2.8.0/lib/rspec/matchers/operator_matcher.rb:59:in `eval_match'
     # /usr/share/gems/gems/rspec-expectations-2.8.0/lib/rspec/matchers/operator_matcher.rb:28:in `block in use_custom_matcher_or_delegate'
     # /tmp/tito-build/rpmbuild-rubygem-scoped_search-b4294a91c7451c618f919cfb92a4b5383ede5a0fmUXQtJ/BUILD/scoped_search-2.4.0/usr/share/gems/gems/scoped_search-2.4.0/spec/integration/string_querying_spec.rb:216:in `block (4 levels) in <top (required)>'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:80:in `instance_eval'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:80:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:173:in `with_around_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:77:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:355:in `block in run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:337:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/reporter.rb:34:in `report'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:25:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:80:in `run_in_process'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:69:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:10:in `block in autorun'

Finished in 0.86039 seconds
241 examples, 1 failure
```

Is is bug in code itself, or just bug in that test?
